version: '3'

services:

    cassandra:
      build:
        context: ./
        dockerfile: docker-cassandra/Dockerfile
      ports:
        - "9042:9042"
      container_name: cassandra
      networks:
        - clientEIS

    api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always
      depends_on:
        - cassandra
      container_name: client-api
      networks:
        - clientEIS

    connect:
      build:
        context: .
        dockerfile: Dockerfile-connect
      restart: always
      depends_on:
        - cassandra
        - zookeeper
        - kafka_node_1
      networks:
        - clientEIS


    zookeeper:
      image: confluentinc/cp-zookeeper:5.4.0
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      networks:
        - clientEIS

    kafka_node_1:
      container_name: kafka_node_1
      image: confluentinc/cp-kafka
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_LISTENERS: "LISTENER_DOCKER_INTERNAL://kafka_node_1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka_node_1}:9092"
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT"
        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_BROKER_ID: 1
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      depends_on:
        - zookeeper
      networks:
        - clientEIS

    kafka-create-topics:
      container_name: kafka-topic-create
      image: confluentinc/cp-enterprise-kafka:5.3.1
      depends_on:
        - zookeeper
        - kafka_node_1
      hostname: kafka-create-topics
      volumes:
        - './seeds/kafka-sample-generator.sh:/kafka-sample-generator.sh'
      entrypoint: "bash kafka-sample-generator.sh"
      environment:
        BROKER_HOST: kafka_node_1
        BROKER_PORT: 19092
        ZOOKEEPER_HOST: zookeeper
        ZOOKEEPER_PORT: 2181
        TOPIC_LIST: client_events,other_events,events
        PARTITIONS: 1,4,3
        REPLICATION_FACTORS: 2,2,2
      networks:
        - clientEIS

networks:
  clientEIS: